@startuml chatSequence

actor user1
user1 -> chat as "チャット送信画面":メッセージ入力
chat -> jinroResponcer:入力メッセージを送信
database Jinro
jinroResponcer -> Jinro:入力メッセージをテーブルに挿入
Broadcast.php <-> Jinro:無限ループで監視
actor user2
Broadcast.php -> user2:JSONでメッセージ送信



@enduml